### ISSUE TITLE
Bug on #6 - Exception on tomcat runtime - Class with Meta-Data not enhanced or multiple jdo-api.jar in CLASSPATH

### ISSUE THREAD

**Issue by ElMesa** [ElMesa/mejorua-api#5]
# BUG on #6  #

Original task: #4 subtask .3
**Actual task: #6 Implement IssueJPADAO with IIssueDAO interface**

    SEVERE: The exception contained within MappableContainerException could not be mapped to a response, re-throwing to the HTTP container
    java.lang.ExceptionInInitializerError
    	at es.ua.dlsi.mejorua.api.resources.IssueCollection.get(IssueCollection.java:40)

    ...

    Caused by: org.datanucleus.exceptions.NucleusUserException: Errors were encountered when     initialising the specified MetaData. See the nested exceptions for details
    	at org.datanucleus.metadata.MetaDataManagerImpl.initialiseFileMetaDataForUse(MetaDataManagerImpl.java:1341)

    ...

    Caused by: org.datanucleus.exceptions.NucleusUserException: Found Meta-Data for class es.ua.dlsi.mejorua.api.transfer.IssueTO but this class is either not enhanced or you have multiple copies of jdo-api.jar in your CLASSPATH!! Make sure all persistable classes are enhanced before running DataNucleus and/or the CLASSPATH is correct.
    	at     org.datanucleus.metadata.MetaDataManagerImpl.initialiseClassMetaData(MetaDataManagerImpl.java:2705)

## Info 

On "mvn clean package" the class seems enhanced

    [INFO] DataNucleus Enhancer (version 4.0.0.release) for API "JPA"

    DataNucleus Enhancer completed with success for 1 classes.

## Tasks

* CHECK the output of enchanced class, maybe trough mvn -X clean package or mejorua-api/logs/datanucleus.log

* CHECK this stackoverflow problem. Is not the same but meybe leads to a solution.

    * http://stackoverflow.com/questions/18056100/datanucleus-jpa-runtime-enhancement-with-tomcat-and-eclipse

**Comment by ElMesa** [comment]
Commit 545850c17d13d6c477fc80ab4e30938375fde6a2 closed #6 
Error no longer apearing.
